/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener cursos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de cursos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Crear curso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Biología",
                     *       "description": "Curso de Biología General"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateCourseRequest"];
                };
            };
            responses: {
                /** @description Curso creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identificador del curso */
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Curso encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matricular usuario en un curso */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    /** @description Identificador del curso */
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "userId": "user-001"
                     *     }
                     */
                    "application/json": components["schemas"]["EnrollmentRequest"];
                };
            };
            responses: {
                /** @description Matrícula creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Enrollment"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear evaluación */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "courseId": "course-001",
                     *       "title": "Evaluación Unidad 1"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateEvaluationRequest"];
                };
            };
            responses: {
                /** @description Evaluación creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Evaluation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realizar una pregunta al Tutor IA */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "courseId": "course-001",
                     *       "question": "¿Qué es la fotosíntesis?"
                     *     }
                     */
                    "application/json": components["schemas"]["TutorQuestionRequest"];
                };
            };
            responses: {
                /** @description Respuesta generada por el Tutor IA */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "answer": "La fotosíntesis es el proceso mediante el cual las plantas producen energía.",
                         *       "sources": [
                         *         "Biología - Unidad 1",
                         *         "Material del curso"
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["TutorQuestionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Course: {
            id: string;
            name: string;
            description?: string;
        };
        CreateCourseRequest: {
            name: string;
            description?: string;
        };
        EnrollmentRequest: {
            userId: string;
        };
        Enrollment: {
            id: string;
            userId: string;
            courseId: string;
        };
        CreateEvaluationRequest: {
            courseId: string;
            title: string;
        };
        Evaluation: {
            id: string;
            courseId: string;
            title: string;
        };
        TutorQuestionRequest: {
            courseId: string;
            question: string;
        };
        TutorQuestionResponse: {
            answer: string;
            sources?: string[];
        };
        Error: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri */
            instance?: string;
        };
    };
    responses: {
        /** @description Solicitud inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description No autorizado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Identificador del curso */
        CourseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
